name: 'Español: Tap & Denise Hornor '
favicon: null
layout_spectrum: 0.6835563152562827
typography_spectrum: 0.42507258942350745
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.09353929944336414
  lightness: 0.5778339356184006
  saturation: 0.11716022528707981
  rhythmicContrast: 0.4993642691988498
purpose: []
